### ISSUE TITLE
"runtime" collides with a plugin of the same name

### ISSUE THREAD

**Issue by joeybaker** [babel-plugins/babel-plugin-runtime#1]
I'm trying to test a project generator, and as a part of the process, I'd like to run babel to ensure that `.babelrc` is generated correctly. When I add this plugin though, I get: `ReferenceError: The plugin "runtime" collides with another of the same name`

Here's the code that's running the test:

```js
const babelPath = path.join(__dirname, '../node_modules/.bin/babel')
const appPath = path.join(testDir, 'index.js')

exec(babelPath, [appPath], {cwd: testDir}, (err) => {
   t.error(err, 'babel does not error')
})
```

**Comment by sebmck** [comment]
For the timebeing this transformer is still embedded in Babel core. Use the `optional` `runtime` transformer which aliases to this plugin.

**Comment by joeybaker** [comment]
Gotcha. Thanks!
